import React from 'react';
import './styles/meeting-number.scss'

function MeetingNumber() {

return(
    <div>
        <header class="sticky navbar bg-light">
                <img class="logoBMS" src="/BMS_Logo_Green.png"/>
        </header>
        <div class="container center">
            <div class="container center mb-10">
                <h1 class="topH1">MEETING NR [[here goes the number generated by react (??)]]</h1>
                <p>here you can choose and check your availability</p>
            </div>
            <div class="container-of-grid">
                <div class="grid-day">
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                    <div class="grid-halfHour"></div>
                </div>
                <div>a</div>
                <div>a</div>
                <div>a</div>
                <div>a</div>
                <div>a</div>
                <div>a</div>
            </div>
        </div>
    </div>
);
    
}

export default MeetingNumber;